/**
 * carimg-lb
 * carimg lb
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<Carbrand>, schemaOptions: { partial: true })
 */
export interface CarbrandPartial { 
    id?: number;
    name?: string;
    country?: string;
}

