/**
 * carimg-lb
 * carimg lb
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: CarbrandWithRelations, schemaOptions: { includeRelations: true })
 */
export interface CarbrandWithRelations { 
    id?: number;
    name: string;
    country?: string;
}

