/**
 * carimg-lb
 * carimg lb
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Carbrand, \'id\'>, schemaOptions: { title: \'NewCarbrand\', exclude: [ \'id\' ] })
 */
export interface NewCarbrand { 
    name: string;
    country?: string;
}

